# Generated by Django 5.2 on 2026-09-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_education_id_alter_experience_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='project_photos/')),
            ],
        ),
    ]
