# Generated by Django 5.2 on 2026-09-27 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_experience_experience_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='experience_image_url',
        ),
        migrations.AddField(
            model_name='education',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_education', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='previouswork',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_previouswork', to=settings.AUTH_USER_MODEL),
        ),
    ]
